# Generated by Django 3.2.9 on 2021-11-30 08:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkExperience', '0002_auto_20211108_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
