# Generated by Django 3.2.9 on 2021-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkExperience', '0004_alter_project_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
