# Generated by Django 3.2.3 on 2022-05-06 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkExperience', '0005_alter_project_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
