# Generated by Django 3.2.3 on 2022-05-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0008_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Skills', 'verbose_name_plural': 'Skills'},
        ),
    ]
